# conf/temp_train_config_1min.yaml
project_name: EscapeRoomDebug1Min
experiment_name: escape_room_gpu_debug_1min_run
raw_data_dir: /data/bookings/
escape_room_datamodule:
  csv_path: /home/evan/Dropbox/Pass Through Files/HQ Booking Data (For EBF).csv
  batch_size: 256
  num_workers: 8
  history_cutoff: "2023-01-01"
model_autogluon:
  target: "y"
  freq: "H"
  prediction_length: 24
  eval_metric: "WAPE"
  time_limit_per_family: 60 # Changed from 120 for a ~1 min run per family
  fit_hyperparameters:
    Chronos:
      model_path: "autogluon/chronos-bolt-base"
      context_length: 168
      batch_size: 8
      fine_tune: true
      epochs: 10
      learning_rate: 3e-5
      lr_scheduler_type: "cosine"
      warmup_ratio: 0.05
      lora_r: 4
      lora_alpha: 8
      trainer_kwargs:
        accelerator: "gpu"
        devices: 1
        precision: "bf16-mixed"
        gradient_checkpointing: true
show_leaderboard: true 